#!/usr/bin/env bash
# configure nginx server so that /redirect_me is redirecting to another page
# redirection must be a "301 Moved Permanently"
# using 1-install_nginx_web_server - write 3-redirection so that it configures
# a brand new ubuntu machine to the requirements in this task
sudo apt-get update -y
sudo apt-get  install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" |  sudo tee file /var/www/html/index.html
sudo sed -i '/server_name _;/a rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
