#!/usr/bin/env bash
# creates a file /var/run/myscript.pid
# display To infinity and beyond
# i hate the klll command
# Y U no love me ?!
# deletes /var/run/myscript.pid

terminator() {
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'terminator' SIGQUIT
done
