#!/usr/bin/env bash
# manage process my_process
# args `start`:
# 1) starts manage_my_process 
# 2) creates file containing its PID in var/run/my_process.pid 
# 3) display "manage_my_process started"
# args `stop`
# 1) stops manage_my_process, then deleting file my_process.pid and display
# "manage_my_process stopped"
# args `restart`
# stops manage_myy_process, deletes my_process.pid, starts manage_my_process
# creates a file my_process_id containing PID
# display "manage_my_process restarted"
# usage: manage_my_process {start|stop|restart}

if [ "$1" == "start" ]
then
	./manage_my_process &
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process started"

elif [ "$1" == "stop" ]
then
#	pkill -f manage_my_process
	kill -s TERM "$(pgrep -f manage-my_process)" &&
	rm /var/run/my_process.pid &&
	echo "manage_my_process stopped"

elif [ "$1" == "restart" ]
then
#	pkill -f manage_my_process
	kill -s TERM "$(pgrep -f manage_my_process)" &&
	rm /var/run/my_process.pid &&
	./maanage_my_process &
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process restarted"

else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
