#!/usr/bin/env bash
# display "To infinity and beyond" indefinitely with sleep(2) on iteration
# display "I am invinvible!!!" in between each iteration

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
