#!/usr/bin/env bash
# fizzbuzz (1-100)
# display: "Fizz" - multiples of 3, "Buzz" of 5, and "Fizzbuzz" of both 3 and 5
# display number otherwise

for num in {1..100}
do
	if ((num % 3 == 0 && num %5 == 0))
	then
		echo "FizzBuzz"
	elif ((num % 3 == 0))
	then
		echo "Fizz"
	elif ((num % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$num"
	fi
done
