#!/usr/bin/env bash
# display the contents of the file `etc/passwd`
# only display username, user id and user home dir path

while read -r passwd;
do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
