#!/usr/bin/env bash
# tells a story on the contents of the `/etc/passwd`

while IFS=':' read username password uid gid info home shell;
do
	echo "The user $username is part of the $gid gang,"\
	"lives in $home and rides $shell."\
	"$uid's place is protected by the passcode $password,"\
	"more info about the user here: $info"
done < "/etc/passwd"
