#!/usr/bin/env bash
# parse apche log files in list format
# group visitors Ip and HTTP status code
# display number of occurences, IP, and HTTP status
# sorted

awk '{ print $1 " " $9 }' apache-access.log | sort | uniq -c | sort -rn
