#!/usr/bin/env bash
# Print "Best School" 10 times, whereby, the 4th is replaced y "bad luck"
# and 8th by "good luck" using while loop and if statements

times=0

while (("times" < 10))
do
	if [ $times -eq 3 ]
	then
		echo "bad luck"
	elif [ $times -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((times++))
done
