#!/usr/bin/env bash
# script that displays numbers 1 to 20 and:
# 	displays 4 and then bad luck from China for the 4th loop iteration
# 	displays 9 and then bad luck from Japan for the 9th loop iteration
# 	displays 17 and then bad luck from Italy for the 17th loop iteration

iterate=1

while [ $iterate -le 20 ]
do
	echo "$iterate"
	case $iterate in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	((iterate++))
done
