#!/usr/bin/env bash
# script thet configure an Ubuntu server with the following requirements
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2 	localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cd -f ~/hosts.new /etc/hosts
